name: junction
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0
  chat_gpt_sdk: ^2.0.0
  speech_to_text: ^6.1.1
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.3
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  flutter_audio_waveforms: ^1.2.1+8
  audio_waveforms: ^1.0.3
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  cached_network_image: ^3.2.3
  circular_bottom_navigation: ^2.3.0
  shared_preferences: ^2.0.18
  enough_mail: ^2.1.1
  googleapis: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/png/k.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/png/k.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/png/k.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/


